name = "LaskaRegistry"
uuid = "8b52f866-a0b4-48aa-8fba-b629886c04a2"
repo = "https://github.com/Laska-jl/LaskaRegistry.git"
description = "Registry for packages in the 'Laska' family"

[packages]
47311fc3-b5d5-4c44-b326-9386a1fd4d79 = { name = "LaskaPlot", path = "L/LaskaPlot" }
9ad29ce2-7782-4744-ab48-6ef9cc0286bb = { name = "LaskaCore", path = "L/LaskaCore" }
de767ba9-e829-4e7c-bf82-062dc00bf36c = { name = "LaskaStats", path = "L/LaskaStats" }
